---
title: "Lebenslauf Dr. Paul Schmidt"
author:
  firstname: Dr. Paul
  lastname: Schmidt
  address: "Hamburg, Deutschland"
  position: "Data Scientist / Biostatistiker"
  contacts:
    - icon: fa envelope
      text: schmidtpaul1989@outlook.com
      url: "mailto:schmidtpaul1989@outlook.com"
    - icon: fa phone
      text: +49 172 3091577
      url: "tel:+491723091577"
    - icon: fa brands linkedin
      text: schmidtpaul1989
      url: "https://www.linkedin.com/in/schmidtpaul1989/"
    - icon: fa brands github
      text: SchmidtPaul
      url: "https://github.com/SchmidtPaul/"
    - icon: fa pencil-square
      text: ResearchGate
      url: "https://www.researchgate.net/profile/Paul_Schmidt17"
format:
  typst:
    shortcodes:
      - src/awesomecv/input-yaml.lua
    template-partials:
      - src/awesomecv/typst-show.typ
      - src/awesomecv/typst-template.typ
    toc: true
keep-typ: false
brand:
  typography:
    base: Arial # Source Sans 3
  color:
    primary: "#00923f"
    link: "#00923f"
  defaults:
    awesomecv-typst:
      font-header: Arial # Roboto
profile-photo: "img/paulzoomcircle.png"
bibliography: "CV/citavi_publications.bib"
# csl: src/apa.csl
link-citations: true
citeproc: true
nocite: '@*'
lang: de
---

```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)
pacman::p_load(here, typstcv)
cv <- readRDS(here::here("CV", "CV_ready.rds"))
source(here::here("CV", "CVhelper-typst.R"))
```

# Berufserfahrung

```{r}
#| output: asis
cv_emit_experience("ger")
```

# Ausbildung

```{r}
#| output: asis
cv_emit_education("ger")
```

# Kompetenzen

```{r}
#| output: asis
cv_emit_skills("ger")
```

# Workshops

```{r}
#| output: asis
cv_emit_workshops()
```

# Publikationen

::: {#refs}
:::
